from django import forms
from .models import Simple, Parametric_Data, Detailed_Data

class Simple(forms.Form):
    file_uuid = forms.CharField(max_length=50) 
    Location = forms.CharField(max_length=50)
    Building_type = forms.CharField(max_length=50)
    Roof_area = forms.CharField(max_length=50)
    Roof_type = forms.CharField(max_length=50)
    Radiant_barrier = forms.CharField(max_length=50)
    Normal_Roof = forms.CharField(max_length=50)
    Cool_roof = forms.CharField(max_length=50)
    HVAC_details = forms.CharField(max_length=50)
    Electricity = forms.IntegerField()
    def clean(self):
        file_uuid = self.cleaned_data.get('file_uuid')
        Location = self.cleaned_data.get('Location')
        Building_type = self.cleaned_data.get('Building_type')
        Roof_area = self.cleaned_data.get('Roof_area')
        Roof_type = self.cleaned_data.get('Roof_type')
        Radiant_barrier = self.cleaned_data.get('Radiant_barrier')
        Normal_Roof  = self.cleaned_data.get('Normal_Roof')
        Cool_roof = self.cleaned_data.get('Cool_roof')
        HVAC_details = self.cleaned_data.get('HVAC_details')
        Electricity = self.cleaned_data.get('Electricity')

class Parametric_Data(forms.Form):
    file_uuid = forms.CharField(max_length=50)
    Location = forms.CharField(max_length=50)
    Building_type = forms.CharField(max_length=50)
    Roof_area = forms.CharField(max_length=50)
    Roof_type = forms.CharField(max_length=50)
    Radiant_barrier = forms.CharField(max_length=50)
    Normal_Roof = forms.CharField(max_length=50)
    Cool_roof = forms.CharField(max_length=50)
    HVAC_details = forms.CharField(max_length=50)
    Electricity = forms.IntegerField()
    def clean(self):
        file_uuid = self.cleaned_data.get('file_uuid')
        Location = self.cleaned_data.get('Location')
        Building_type = self.cleaned_data.get('Building_type')
        Roof_area = self.cleaned_data.get('Roof_area')
        Roof_type = self.cleaned_data.get('Roof_type')
        Radiant_barrier = self.cleaned_data.get('Radiant_barrier')
        Normal_Roof  = self.cleaned_data.get('Normal_Roof')
        Cool_roof = self.cleaned_data.get('Cool_roof')
        HVAC_details = self.cleaned_data.get('HVAC_details')
        Electricity = self.cleaned_data.get('Electricity')
        
class Detailed_Data(forms.Form):
    file_uuid = forms.CharField(max_length=50)
    Location = forms.CharField(max_length=50)
    Building_type = forms.CharField(max_length=50)
    Roof_area = forms.CharField(max_length=50)
    Roof_type = forms.CharField(max_length=50)
    Radiant_barrier = forms.CharField(max_length=50)
    Normal_Roof = forms.CharField(max_length=50)
    Cool_roof = forms.CharField(max_length=50)
    HVAC_details = forms.CharField(max_length=50)
    Electricity = forms.IntegerField()
    def clean(self):
        file_uuid = self.cleaned_data.get('file_uuid')
        Location = self.cleaned_data.get('Location')
        Building_type = self.cleaned_data.get('Building_type')
        Roof_area = self.cleaned_data.get('Roof_area')
        Roof_type = self.cleaned_data.get('Roof_type')
        Radiant_barrier = self.cleaned_data.get('Radiant_barrier')
        Normal_Roof  = self.cleaned_data.get('Normal_Roof')
        Cool_roof = self.cleaned_data.get('Cool_roof')
        HVAC_details = self.cleaned_data.get('HVAC_details')
        Electricity = self.cleaned_data.get('Electricity')

