# Generated by Django 2.1.1 on 2018-09-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=50)),
                ('Building_type', models.CharField(max_length=50)),
                ('Roof_area', models.IntegerField(max_length=20)),
                ('Roof_type', models.CharField(max_length=50)),
                ('Radiant_barrier', models.BooleanField(default=False)),
                ('Normal_Roof', models.CharField(max_length=50)),
                ('Cool_roof', models.CharField(max_length=50)),
                ('HVAC_details', models.CharField(max_length=50)),
                ('Electricity', models.IntegerField(max_length=4)),
            ],
        ),
    ]
