# Generated by Django 2.1.1 on 2018-09-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple',
            name='Electricity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='simple',
            name='Roof_area',
            field=models.IntegerField(),
        ),
    ]
