# Generated by Django 2.1.1 on 2018-09-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0002_auto_20180920_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple',
            name='Electricity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='simple',
            name='Roof_area',
            field=models.CharField(max_length=50),
        ),
    ]
