# Generated by Django 2.1.1 on 2018-09-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0003_auto_20180921_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple',
            name='Radiant_barrier',
            field=models.CharField(max_length=10),
        ),
    ]
