# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0007_auto_20180928_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uuid', models.CharField(default=b'0000000', editable=False, max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Building_type', models.CharField(max_length=50)),
                ('Roof_area', models.CharField(max_length=50)),
                ('Layer_1', models.CharField(max_length=50)),
                ('Layer_2', models.CharField(max_length=50)),
                ('Layer_3', models.CharField(max_length=50)),
                ('Layer_4', models.CharField(max_length=50)),
                ('Radiant_barrier', models.CharField(max_length=10)),
                ('Reflectivity_base', models.CharField(max_length=50)),
                ('Emissivity_base', models.CharField(max_length=50)),
                ('Cost_base', models.CharField(max_length=50)),
                ('Life_base', models.CharField(max_length=50)),
                ('Reflectivity_proposed', models.CharField(max_length=50)),
                ('Emissivity_proposed', models.CharField(max_length=50)),
                ('Cost_proposed', models.CharField(max_length=50)),
                ('Life_proposed', models.CharField(max_length=50)),
                ('System_cop', models.CharField(max_length=50)),
                ('Lighting_power', models.CharField(max_length=50)),
                ('Equipment_power', models.CharField(max_length=50)),
                ('win_area_north', models.CharField(max_length=50)),
                ('win_area_south', models.CharField(max_length=50)),
                ('win_area_west', models.CharField(max_length=50)),
                ('win_area_east', models.CharField(max_length=50)),
                ('HVAC_details', models.CharField(max_length=50)),
                ('Electricity', models.CharField(max_length=50)),
            ],
        ),
    ]
