# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-28 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0009_detailed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_data',
            name='cooling_compare',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='heating_compre',
            field=models.CharField(default=b'y', max_length=50),
        ),
    ]
