# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0010_auto_20181028_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_data',
            name='cooling_compare',
            field=models.CharField(default=b'x', max_length=1000),
        ),
        migrations.AlterField(
            model_name='detailed_data',
            name='heating_compre',
            field=models.CharField(default=b'y', max_length=1000),
        ),
    ]
