# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-28 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0012_auto_20181028_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailed_data',
            old_name='heating_compre',
            new_name='heating_compare',
        ),
    ]
