# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-28 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0013_auto_20181028_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_data',
            name='Annual_Savings',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Cooling_Base',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Cooling_Proposed',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Cooling_Savings',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Fans_Base',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Fans_Proposed',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Fans_Savings',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Heat_Rejection_Base',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Heat_Rejection_Proposed',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Heat_Rejection_Savings',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Heating_Base',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Heating_Proposed',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Heating_Savings',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Interior_Equipment_Base',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Interior_Equipment_Proposed',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Interior_Equipment_Savings',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Interior_Lighting_Base',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Interior_Lighting_Proposed',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Interior_Lighting_Savings',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Pumps_Base',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Pumps_Proposed',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Pumps_Savings',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Total_Base',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Total_Proposed',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='Total_Savings',
            field=models.CharField(default=b'x', max_length=50),
        ),
        migrations.AlterField(
            model_name='detailed_data',
            name='heating_compare',
            field=models.TextField(default=b'x', max_length=1000),
        ),
    ]
