# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-31 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0014_auto_20181029_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_data',
            name='task_id',
            field=models.CharField(default='asdasd', max_length=100),
            preserve_default=False,
        ),
    ]
