# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-31 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0015_detailed_data_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed_data',
            name='task_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
