# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-31 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0016_auto_20181031_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_data',
            name='Total_Savings_Percent',
            field=models.CharField(default=b'x', max_length=50),
        ),
    ]
