# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-04 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0017_detailed_data_total_savings_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple',
            name='task_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
