# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-04 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0019_auto_20181104_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple',
            name='Cool_roof_e',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simple',
            name='Normal_Roof_e',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
