# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-04 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0020_auto_20181104_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_data',
            name='kvalue',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
