# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-04 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0021_detailed_data_kvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametric_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uuid', models.CharField(default=b'0000000', editable=False, max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Building_type', models.CharField(max_length=50)),
                ('Roof_area', models.CharField(max_length=50)),
                ('Layer_1', models.CharField(max_length=50)),
                ('Layer_2', models.CharField(max_length=50)),
                ('Layer_3', models.CharField(max_length=50)),
                ('Layer_4', models.CharField(max_length=50)),
                ('Radiant_barrier', models.CharField(max_length=10)),
                ('Reflectivity_base', models.CharField(max_length=50)),
                ('Emissivity_base', models.CharField(max_length=50)),
                ('Cost_base', models.CharField(max_length=50)),
                ('Life_base', models.CharField(max_length=50)),
                ('Reflectivity_proposed', models.CharField(max_length=50)),
                ('Emissivity_proposed', models.CharField(max_length=50)),
                ('Cost_proposed', models.CharField(max_length=50)),
                ('Life_proposed', models.CharField(max_length=50)),
                ('System_cop', models.CharField(max_length=50)),
                ('Lighting_power', models.CharField(max_length=50)),
                ('Equipment_power', models.CharField(max_length=50)),
                ('win_area_north', models.CharField(max_length=50)),
                ('win_area_south', models.CharField(max_length=50)),
                ('win_area_west', models.CharField(max_length=50)),
                ('win_area_east', models.CharField(max_length=50)),
                ('HVAC_details', models.CharField(max_length=50)),
                ('Electricity', models.CharField(max_length=50)),
                ('cooling_compare', models.TextField(default=b'x', max_length=1000)),
                ('heating_compare', models.TextField(default=b'x', max_length=1000)),
                ('Total_Savings', models.CharField(default=b'x', max_length=50)),
                ('Total_Savings_Percent', models.CharField(default=b'x', max_length=50)),
                ('Annual_Savings', models.CharField(default=b'x', max_length=50)),
                ('Heating_Base', models.CharField(default=b'x', max_length=50)),
                ('Heating_Proposed', models.CharField(default=b'x', max_length=50)),
                ('Heating_Savings', models.CharField(default=b'x', max_length=50)),
                ('Cooling_Base', models.CharField(default=b'x', max_length=50)),
                ('Cooling_Proposed', models.CharField(default=b'x', max_length=50)),
                ('Cooling_Savings', models.CharField(default=b'x', max_length=50)),
                ('Interior_Equipment_Base', models.CharField(default=b'x', max_length=50)),
                ('Interior_Equipment_Proposed', models.CharField(default=b'x', max_length=50)),
                ('Interior_Equipment_Savings', models.CharField(default=b'x', max_length=50)),
                ('Interior_Lighting_Base', models.CharField(default=b'x', max_length=50)),
                ('Interior_Lighting_Proposed', models.CharField(default=b'x', max_length=50)),
                ('Interior_Lighting_Savings', models.CharField(default=b'x', max_length=50)),
                ('Fans_Base', models.CharField(default=b'x', max_length=50)),
                ('Fans_Proposed', models.CharField(default=b'x', max_length=50)),
                ('Fans_Savings', models.CharField(default=b'x', max_length=50)),
                ('Pumps_Base', models.CharField(default=b'x', max_length=50)),
                ('Pumps_Proposed', models.CharField(default=b'x', max_length=50)),
                ('Pumps_Savings', models.CharField(default=b'x', max_length=50)),
                ('Heat_Rejection_Base', models.CharField(default=b'x', max_length=50)),
                ('Heat_Rejection_Proposed', models.CharField(default=b'x', max_length=50)),
                ('Heat_Rejection_Savings', models.CharField(default=b'x', max_length=50)),
                ('Total_Base', models.CharField(default=b'x', max_length=50)),
                ('Total_Proposed', models.CharField(default=b'x', max_length=50)),
                ('kvalue', models.CharField(max_length=50)),
                ('task_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='detailed_data',
            name='kvalue',
        ),
    ]
