# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0024_auto_20181106_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple',
            name='emailid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
