# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-14 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0025_simple_emailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_data',
            name='emailid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parametric_data',
            name='emailid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
