# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-15 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0026_auto_20181114_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
