# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-15 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0027_simple_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simple',
            old_name='user_name',
            new_name='user_email',
        ),
        migrations.AddField(
            model_name='detailed_data',
            name='user_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parametric_data',
            name='user_email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
