# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0028_auto_20181115_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
