# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0031_auto_20181116_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simple',
            old_name='user_email',
            new_name='user_id',
        ),
    ]
