# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0032_auto_20181117_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simple',
            old_name='user_id',
            new_name='userid',
        ),
    ]
