# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-16 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0034_auto_20181117_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simple',
            old_name='user_email',
            new_name='username',
        ),
    ]
