# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-18 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0036_auto_20181118_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailed_data',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='parametric_data',
            name='user_email',
        ),
    ]
