# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-18 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0037_auto_20181118_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detailed',
        ),
    ]
