# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-18 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import datetime
from django.utils.timezone import make_aware

utc = datetime.timezone.utc  # ✅ Use Python's built-in UTC timezone



class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0039_detailed_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametric_data',
            name='time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 11, 18, 10, 5, 44, 965547, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
