# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-20 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0040_parametric_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed_data',
            name='result_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parametric_data',
            name='result_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
