# Generated by Django 5.1.7 on 2025-03-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Calculator", "0041_auto_20181120_1838"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailed_data",
            name="Annual_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Cooling_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Cooling_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Cooling_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Fans_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Fans_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Fans_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Heat_Rejection_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Heat_Rejection_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Heat_Rejection_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Heating_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Heating_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Heating_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Interior_Equipment_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Interior_Equipment_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Interior_Equipment_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Interior_Lighting_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Interior_Lighting_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Interior_Lighting_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Pumps_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Pumps_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Pumps_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Total_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Total_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Total_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="Total_Savings_Percent",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="cool_save",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="cool_save_area",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="cool_save_cost",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="cooling_compare",
            field=models.TextField(default="x", max_length=1000),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="file_uuid",
            field=models.CharField(default="0000000", editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="heat_save",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="heat_save_area",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="heat_save_cost",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="heating_compare",
            field=models.TextField(default="x", max_length=1000),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="total_save",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="total_save_area",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="detailed_data",
            name="total_save_cost",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Annual_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Cooling_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Cooling_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Cooling_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Fans_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Fans_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Fans_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Heat_Rejection_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Heat_Rejection_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Heat_Rejection_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Heating_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Heating_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Heating_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Interior_Equipment_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Interior_Equipment_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Interior_Equipment_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Interior_Lighting_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Interior_Lighting_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Interior_Lighting_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Pumps_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Pumps_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Pumps_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Total_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Total_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Total_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="Total_Savings_Percent",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="cool_save",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="cool_save_area",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="cool_save_cost",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="cooling_compare",
            field=models.TextField(default="x", max_length=1000),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="file_uuid",
            field=models.CharField(default="0000000", editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="heat_save",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="heat_save_area",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="heat_save_cost",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="heating_compare",
            field=models.TextField(default="x", max_length=1000),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="total_save",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="total_save_area",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="parametric_data",
            name="total_save_cost",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Annual_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Cooling_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Cooling_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Cooling_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Fans_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Fans_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Fans_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Heat_Rejection_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Heat_Rejection_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Heat_Rejection_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Heating_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Heating_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Heating_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Interior_Equipment_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Interior_Equipment_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Interior_Equipment_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Interior_Lighting_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Interior_Lighting_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Interior_Lighting_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Pumps_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Pumps_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Pumps_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Total_Base",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Total_Proposed",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Total_Savings",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="Total_Savings_Percent",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="cool_save",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="cool_save_area",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="cool_save_cost",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="cooling_compare",
            field=models.TextField(default="x", max_length=1000),
        ),
        migrations.AlterField(
            model_name="simple",
            name="file_uuid",
            field=models.CharField(default="0000000", editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="heat_save",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="heat_save_area",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="heat_save_cost",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="heating_compare",
            field=models.TextField(default="x", max_length=1000),
        ),
        migrations.AlterField(
            model_name="simple",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="simple",
            name="total_save",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="total_save_area",
            field=models.CharField(default="x", max_length=50),
        ),
        migrations.AlterField(
            model_name="simple",
            name="total_save_cost",
            field=models.CharField(default="x", max_length=50),
        ),
    ]
